name: Vibrant Equity
favicon: null
layout_spectrum: 0.508996884804219
typography_spectrum: 0.2983447816222906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20742536219768226
  lightness: 0.7334192874841392
  saturation: 0.5060091698542237
  rhythmicContrast: 0.322345535736531
purpose: []
