typography_spectrum: 0.2983447816222906
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.7334192874841392
  saturation: 0.5060091698542237
  rhythmicContrast: 0.322345535736531
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.508996884804219
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: Vibrant Equity
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Vibrant Equity
purpose: []
